export const junctionClerkAppearance = {
  variables: {
    colorPrimary: "#111111",
    colorBackground: "#FFFFFF",
    colorText: "#111111",
    colorTextSecondary: "#666666",
    colorInputBackground: "#F6F4EE",
    colorInputText: "#111111",
    colorDanger: "#DC2626",
    borderRadius: "2px",
    fontFamily: "'Space Grotesk', 'Inter', -apple-system, sans-serif",
  },
  elements: {
    rootBox: {
      width: "100%",
      maxWidth: "460px",
      margin: "0 auto",
    },
    card: {
      border: "1px solid #111111",
      boxShadow: "4px 4px 0px #111111",
      borderRadius: "2px",
      backgroundColor: "#FFFFFF",
      padding: "32px 28px",
    },
    headerTitle: {
      fontFamily: "'Space Grotesk', sans-serif",
      fontWeight: 800,
      fontSize: "22px",
      letterSpacing: "-0.01em",
      color: "#111111",
    },
    headerSubtitle: {
      fontFamily: "'Inter', sans-serif",
      color: "#666666",
      fontSize: "13px",
      marginTop: "4px",
    },
    socialButtonsBlockButton: {
      borderRadius: "2px",
      border: "1px solid #111111",
      boxShadow: "2px 2px 0px #111111",
      fontFamily: "'Space Grotesk', sans-serif",
      fontWeight: 700,
      fontSize: "13px",
      backgroundColor: "#FFFFFF",
      color: "#111111",
      transition: "all 0.15s ease",
      "&:hover": {
        backgroundColor: "#F6F4EE",
        transform: "translate(-1px, -1px)",
        boxShadow: "3px 3px 0px #111111",
      },
    },
    dividerLine: {
      backgroundColor: "#CCCAB8",
    },
    dividerText: {
      color: "#888888",
      fontFamily: "'Space Grotesk', sans-serif",
      fontSize: "11px",
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: "0.06em",
    },
    formFieldLabel: {
      fontFamily: "'Space Grotesk', sans-serif",
      fontWeight: 700,
      fontSize: "11px",
      letterSpacing: "0.05em",
      textTransform: "uppercase",
      color: "#111111",
    },
    formFieldInput: {
      borderRadius: "2px",
      border: "1px solid #111111",
      backgroundColor: "#F6F4EE",
      fontFamily: "'Inter', sans-serif",
      fontSize: "14px",
      color: "#111111",
      "&:focus": {
        borderColor: "#111111",
        outline: "2px solid #F5C400",
      },
    },
    formButtonPrimary: {
      backgroundColor: "#111111",
      color: "#FFFFFF",
      borderRadius: "2px",
      border: "1px solid #111111",
      fontFamily: "'Space Grotesk', sans-serif",
      fontWeight: 800,
      fontSize: "13px",
      letterSpacing: "0.06em",
      textTransform: "uppercase",
      padding: "12px",
      boxShadow: "2px 2px 0px #F5C400",
      transition: "all 0.15s ease",
      "&:hover": {
        backgroundColor: "#2E2E2E",
        transform: "translate(-1px, -1px)",
        boxShadow: "3px 3px 0px #F5C400",
      },
    },
    footerActionLink: {
      color: "#111111",
      fontWeight: 700,
      textDecoration: "underline",
      "&:hover": {
        color: "#997A00",
      },
    },
    identityPreviewText: {
      fontFamily: "'Inter', sans-serif",
      color: "#111111",
    },
  },
};
